/** Конфигурация всех разделов тестов ПДД ПМР */
module.exports = {
  groups: [
    { id: 'rules', title: 'Правила дорожного движения', icon: '📜', desc: 'Общие положения, обязанности, сигналы светофора и регулировщика' },
    { id: 'maneuvers', title: 'Маневрирование и движение', icon: '🔄', desc: 'Манёвры, скорость, обгон, остановка и расположение на дороге' },
    { id: 'crossings', title: 'Перекрёстки и переходы', icon: '✖️', desc: 'Перекрёстки, переходы, ж/д, автомагистрали, перевозка' },
    { id: 'signs', title: 'Дорожные знаки', icon: '🪧', desc: 'Все категории дорожных знаков ПДД ПМР' },
    { id: 'marking', title: 'Дорожная разметка', icon: '➖', desc: 'Горизонтальная и вертикальная разметка' },
    { id: 'other', title: 'Безопасность и ответственность', icon: '🛡️', desc: 'Безопасное вождение, первая помощь, ответственность' },
  ],

  categories: [
    { id: 'general-provisions', group: 'rules', icon: '📋', title: 'Общие положения', desc: 'Термины и основные понятия ПДД ПМР', source: 'Общие положения.json' },
    { id: 'driver-duties', group: 'rules', icon: '👤', title: 'Общие обязанности водителей', desc: 'Обязанности и запреты для водителя', source: 'Общие обязанности водителей.json' },
    { id: 'special-signals', group: 'rules', icon: '🚨', title: 'Применение специальных сигналов', desc: 'Проблесковые маячки и спецтранспорт', source: 'Применение специальных сигналов.json' },
    { id: 'traffic-signals', group: 'rules', icon: '🚦', title: 'Сигналы светофора и регулировщика', desc: 'Общие правила сигналов', source: 'Сигналы светофора и регулировщика.json' },
    { id: 'traffic-light', group: 'rules', icon: '🔴', title: 'Сигналы светофора', desc: 'Значения сигналов светофора', source: 'Сигналы светофора и регулировщика.json', filter: t => /светофор/i.test(t) && !/регулировщик/i.test(t) },
    { id: 'regulator', group: 'rules', icon: '🧑‍✈️', title: 'Сигналы регулировщика', desc: 'Жесты и указания регулировщика', source: 'Сигналы светофора и регулировщика.json', filter: t => /регулировщик/i.test(t) },
    { id: 'emergency-signals', group: 'rules', icon: '⚠️', title: 'Аварийная сигнализация', desc: 'Знак аварийной остановки и «аварийка»', source: 'Применение аварийной сигнализации и знака аварийной остановки.json' },

    { id: 'maneuvering', group: 'maneuvers', icon: '🔄', title: 'Начало движения, маневрирование', desc: 'Общие правила маневров', source: 'Начало движения, маневрирование.json' },
    { id: 'turn-signals', group: 'maneuvers', icon: '↔️', title: 'Указатели поворота', desc: 'Световые указатели поворота', source: 'Начало движения, маневрирование.json', filter: t => /указател/i.test(t) },
    { id: 'start-lane-change', group: 'maneuvers', icon: '⏵', title: 'Начало движения, перестроение', desc: 'Выезд и смена полосы', source: 'Начало движения, маневрирование.json', filter: t => /начал|перестро|выезд|выезж|полос/i.test(t) && !/разворот|задним/i.test(t) },
    { id: 'turns', group: 'maneuvers', icon: '↪️', title: 'Повороты', desc: 'Правила выполнения поворотов', source: 'Начало движения, маневрирование.json', filter: t => /поворот/i.test(t) && !/разворот|указател/i.test(t) },
    { id: 'u-turn', group: 'maneuvers', icon: '🔃', title: 'Разворот', desc: 'Правила разворота', source: 'Начало движения, маневрирование.json', filter: t => /разворот/i.test(t) },
    { id: 'reverse', group: 'maneuvers', icon: '⏪', title: 'Задний ход', desc: 'Движение задним ходом', source: 'Начало движения, маневрирование.json', filter: t => /задним ход/i.test(t) },
    { id: 'lane-position', group: 'maneuvers', icon: '🛣️', title: 'Расположение ТС на проезжей части', desc: 'Полосы и расположение на дороге', source: 'Расположение транспортных средств на проезжей части.json' },
    { id: 'speed', group: 'maneuvers', icon: '⏱️', title: 'Скорость движения', desc: 'Ограничения и выбор скорости', source: 'Скорость движения.json' },
    { id: 'overtaking', group: 'maneuvers', icon: '🏎️', title: 'Обгон, встречный разъезд', desc: 'Обгон, опережение, разъезд', source: 'Обгон, опережение, встречный разъезд.json' },
    { id: 'parking', group: 'maneuvers', icon: '🅿️', title: 'Остановка и стоянка', desc: 'Где и как останавливаться', source: 'Остановка и стоянка.json' },

    { id: 'intersections', group: 'crossings', icon: '✖️', title: 'Проезд перекрёстков', desc: 'Общие правила перекрёстков', source: 'Проезд перекрестков.json' },
    { id: 'intersections-regulated', group: 'crossings', icon: '🚥', title: 'Регулируемые перекрёстки', desc: 'Перекрёстки со светофором', source: 'Проезд перекрестков.json', filter: t => /регулиру|светофор/i.test(t) },
    { id: 'intersections-equal', group: 'crossings', icon: '⚖️', title: 'Равнозначные перекрёстки', desc: '«Правило правой руки»', source: 'Проезд перекрестков.json', filter: t => /равнознач/i.test(t) },
    { id: 'intersections-unequal', group: 'crossings', icon: '🔶', title: 'Неравнозначные перекрёстки', desc: 'Главная и второстепенная дорога', source: 'Проезд перекрестков.json', filter: t => /неравнознач|главн|второстепен|уступ/i.test(t) && !/равнознач/i.test(t) },
    { id: 'crosswalks', group: 'crossings', icon: '🚶', title: 'Пешеходные переходы', desc: 'Переходы и остановки маршрутных ТС', source: 'Пешеходные переходы и места остановок маршрутных транспортных средств.json' },
    { id: 'railway', group: 'crossings', icon: '🚂', title: 'Железнодорожные переезды', desc: 'Проезд через ж/д пути', source: 'Движение через железнодорожные пути.json' },
    { id: 'highways', group: 'crossings', icon: '🛣️', title: 'Автомагистрали', desc: 'Движение по автомагистралям', source: 'Движение по автомагистралям.json' },
    { id: 'residential', group: 'crossings', icon: '🏘️', title: 'Жилые и пешеходные зоны', desc: 'Движение в жилых зонах', source: 'Движение в жилых зонах.json' },
    { id: 'route-priority', group: 'crossings', icon: '🚌', title: 'Приоритет маршрутных ТС', desc: 'Автобусы и трамваи', source: 'Приоритет маршрутных транспортных средств.json' },
    { id: 'lights-horn', group: 'crossings', icon: '💡', title: 'Световые приборы и звук', desc: 'Фары, габариты, звуковой сигнал', source: 'Пользование внешними световыми приборами и звуковыми сигналами.json' },
    { id: 'towing', group: 'crossings', icon: '🔗', title: 'Буксировка', desc: 'Буксировка механических ТС', source: 'Буксировка механических транспортных средств.json' },
    { id: 'training', group: 'crossings', icon: '🎓', title: 'Учебная езда', desc: 'Обучение вождению', source: 'Учебная езда и дополнительные требования к движению велосипедистов.json', filter: t => /учебн/i.test(t) },
    { id: 'cargo-people', group: 'crossings', icon: '📦', title: 'Перевозка людей и грузов', desc: 'Правила перевозки', source: 'Перевозка людей и грузов.json' },
    { id: 'cyclists', group: 'crossings', icon: '🚲', title: 'Велосипедисты и мопеды', desc: 'Доп. требования к велосипедистам', source: 'Учебная езда и дополнительные требования к движению велосипедистов.json', filter: t => /велосипед|мопед/i.test(t) },

    { id: 'signs-warning', group: 'signs', icon: '⚠️', title: 'Предупреждающие знаки', desc: 'Знаки серии 1.x', signPrefix: /^1\./ },
    { id: 'signs-priority', group: 'signs', icon: '🔶', title: 'Знаки приоритета', desc: 'Знаки серии 2.x', signPrefix: /^2\./ },
    { id: 'signs-prohibition', group: 'signs', icon: '🚫', title: 'Запрещающие знаки', desc: 'Знаки серии 3.x', signPrefix: /^3\./ },
    { id: 'signs-mandatory', group: 'signs', icon: '🔵', title: 'Предписывающие знаки', desc: 'Знаки серии 4.x', signPrefix: /^4\./ },
    { id: 'signs-special', group: 'signs', icon: '🟦', title: 'Знаки особых предписаний', desc: 'Знаки серии 5.x', signPrefix: /^5\./ },
    { id: 'signs-info', group: 'signs', icon: '🔷', title: 'Информационные знаки', desc: 'Знаки серии 6.x', signPrefix: /^6\./ },
    { id: 'signs-service', group: 'signs', icon: '🛎️', title: 'Знаки сервиса', desc: 'Знаки серии 7.x', signPrefix: /^7\./ },
    { id: 'signs-additional', group: 'signs', icon: '📋', title: 'Знаки доп. информации', desc: 'Таблички 8.x', signPrefix: /^8\./ },

    { id: 'marking', group: 'marking', icon: '〰️', title: 'Дорожная разметка', desc: 'Горизонтальная и вертикальная', source: 'Дорожная разметка.json' },
    { id: 'marking-horizontal', group: 'marking', icon: '➖', title: 'Горизонтальная разметка', desc: 'Линии и символы на проезжей части', source: 'Дорожная разметка.json', filter: t => /разметк|1\.\d|горизонт|линия|полос/i.test(t) && !/вертикал|столб|2\.\d/i.test(t) },
    { id: 'marking-vertical', group: 'marking', icon: '📏', title: 'Вертикальная разметка', desc: 'Чёрно-белые полосы на опорах', source: 'Дорожная разметка.json', filter: t => /вертикал|столб|2\.\d/i.test(t) },

    { id: 'defects', group: 'other', icon: '🔧', title: 'Неисправности ТС', desc: 'Запрет эксплуатации', source: 'Неисправности и условия допуска транспортных средств к эксплуатации.json' },
    { id: 'safe-driving', group: 'other', icon: '🛡️', title: 'Безопасное управление', desc: 'Техника управления автомобилем', source: 'Безопасность движения и техника управления автомобилем.json' },
    { id: 'first-aid', group: 'other', icon: '🏥', title: 'Первая помощь', desc: 'Доврачебная помощь пострадавшим', source: 'Оказание доврачебной медицинской помощи.json' },
    { id: 'responsibility', group: 'other', icon: '⚖️', title: 'Ответственность водителя', desc: 'Административная ответственность', source: 'Ответственность водителя.json' },
  ],

  theoryChapters: [
    { id: 'general-provisions', title: 'Общие положения', slug: 'пдд-пмр-общие-положения', section: '1' },
    { id: 'driver-duties', title: 'Общие обязанности водителей', slug: 'пдд-пмр-общие-обязанности-водителей', section: '2' },
    { id: 'special-signals', title: 'Применение специальных сигналов', slug: 'пдд-пмр-применение-специальных-сигналов', section: '3' },
    { id: 'pedestrian-duties', title: 'Обязанности пешеходов', slug: 'пдд-пмр-обязанности-пешеходов', section: '4' },
    { id: 'passenger-duties', title: 'Обязанности пассажиров', slug: 'пдд-пмр-обязанности-пассажиров', section: '5' },
    { id: 'traffic-signals', title: 'Сигналы светофора и регулировщика', slug: 'пдд-пмр-сигналы-светофора-и-регулировщика', section: '6' },
    { id: 'emergency-signals', title: 'Аварийная сигнализация и знак остановки', slug: 'пдд-пмр-применение-аварийной-сигнализации-и-знака-аварийной-остановки', section: '7' },
    { id: 'maneuvering', title: 'Начало движения, маневрирование', slug: 'пдд-пмр-начало-движения-маневрирование', section: '8' },
    { id: 'lane-position', title: 'Расположение ТС на проезжей части', slug: 'пдд-пмр-расположение-транспортных-средств-на-проезжей-части', section: '9' },
    { id: 'speed', title: 'Скорость движения', slug: 'пдд-пмр-скорость-движения', section: '10' },
    { id: 'overtaking', title: 'Обгон, встречный разъезд', slug: 'пдд-пмр-обгон-встречный-разъезд', section: '11' },
    { id: 'parking', title: 'Остановка и стоянка', slug: 'пдд-пмр-остановка-и-стоянка', section: '12' },
    { id: 'intersections', title: 'Проезд перекрестков', slug: 'пдд-пмр-проезд-перекрестков', section: '13' },
    { id: 'crosswalks', title: 'Пешеходные переходы', slug: 'пдд-пмр-пешеходные-переходы-и-места-остановок-маршрутных-транспортных-средств', section: '14' },
    { id: 'railway', title: 'Железнодорожные переезды', slug: 'пдд-пмр-движение-через-железнодорожные-пути', section: '15' },
    { id: 'highways', title: 'Автомагистрали', slug: 'пдд-пмр-движение-по-автомагистралям-и-дорогам-для-автомобилей', section: '16' },
    { id: 'residential', title: 'Жилые и пешеходные зоны', slug: 'пдд-пмр-движение-в-жилой-и-пешеходной-зонах', section: '17' },
    { id: 'route-priority', title: 'Приоритет маршрутных ТС', slug: 'пдд-пмр-приоритет-маршрутных-транспортных-средств', section: '18' },
    { id: 'lights-horn', title: 'Световые приборы и звук', slug: 'пдд-пмр-пользование-внешними-световыми-приборами-и-звуковыми-сигналами', section: '19' },
    { id: 'towing', title: 'Буксировка', slug: 'пдд-пмр-буксировка-механических-транспортных-средств', section: '20' },
    { id: 'training', title: 'Учебная езда', slug: 'пдд-пмр-учебная-езда', section: '21' },
    { id: 'cargo-people', title: 'Перевозка людей', slug: 'пдд-пмр-перевозка-людей', section: '22' },
    { id: 'cargo-goods', title: 'Перевозка грузов', slug: 'пдд-пмр-перевозка-грузов', section: '23' },
    { id: 'cyclists', title: 'Велосипедисты и мопеды', slug: 'пдд-пмр-дополнительные-требования-к-движению-велосипедистов-водителей-мопедов', section: '24' },
    { id: 'horse-vehicles', title: 'Гужевой транспорт и животные', slug: 'пдд-пмр-дополнительные-требования-к-движению-гужевых-повозок', section: '25' },
    { id: 'appendix1', title: 'Приложение 1. Неисправности', slug: 'пдд-пмр-приложение-1-перечень-неисправностей', section: 'П1', parent: 'appendix' },
    { id: 'appendix2', title: 'Приложение 2. Допуск ТС', slug: 'пдд-пмр-приложение-2-основные-положения-по-допуску', section: 'П2', parent: 'appendix' },
    { id: 'signs-intro', title: 'Дорожные знаки', slug: 'пдд-пмр-дорожные-знаки', section: 'З', parent: 'signs' },
    { id: 'signs-warning', title: 'Предупреждающие знаки', slug: 'пдд-пмр-предупреждающие-знаки', section: '1', parent: 'signs' },
    { id: 'signs-priority', title: 'Знаки приоритета', slug: 'пдд-пмр-знаки-приоритета', section: '2', parent: 'signs' },
    { id: 'signs-prohibition', title: 'Запрещающие знаки', slug: 'пдд-пмр-запрещающие-знаки', section: '3', parent: 'signs' },
    { id: 'signs-mandatory', title: 'Предписывающие знаки', slug: 'пдд-пмр-предписывающие-знаки', section: '4', parent: 'signs' },
    { id: 'signs-special', title: 'Знаки особых предписаний', slug: 'пдд-пмр-знаки-особых-предписаний', section: '5', parent: 'signs' },
    { id: 'signs-info', title: 'Информационные знаки', slug: 'пдд-пмр-информационные-знаки', section: '6', parent: 'signs' },
    { id: 'signs-service', title: 'Знаки сервиса', slug: 'пдд-пмр-знаки-сервиса', section: '7', parent: 'signs' },
    { id: 'signs-additional', title: 'Знаки доп. информации', slug: 'пдд-пмр-знаки-дополнительной-информации', section: '8', parent: 'signs' },
    { id: 'marking-intro', title: 'Дорожная разметка', slug: 'пдд-пмр-дорожная-разметка', section: 'Р', parent: 'marking' },
    { id: 'marking-horizontal', title: 'Горизонтальная разметка', slug: 'пдд-пмр-горизонтальная-разметка', section: 'Г', parent: 'marking' },
    { id: 'marking-vertical', title: 'Вертикальная разметка', slug: 'пдд-пмр-вертикальная-разметка', section: 'В', parent: 'marking' },
  ],
};
